[project]
name = 'Blockchain-Inventory-System'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Stacks-Gaming-Assets]
path = 'contracts/Stacks-Gaming-Assets.clar'
clarity_version = 2
epoch = 2.5

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
